import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const defaultRepoRoot = resolve(scriptDir, '..', '..')
const versionPattern = /^\d+\.\d+\.\d+-beta\.\d+(?:\.\d+)*$/

export function validateAppVersion(version) {
  if (!versionPattern.test(version)) {
    throw new Error(`Invalid version "${version}"; expected format x.y.z-beta.n[.n]`)
  }
  return version
}

export function bumpVersion(version) {
  validateAppVersion(version)
  return version.replace(/(\.)(\d+)$/, (_match, separator, value) => {
    return `${separator}${Number(value) + 1}`
  })
}

export async function syncVersion({ repoRoot = defaultRepoRoot, nextVersion }) {
  const version = validateAppVersion(nextVersion)
  const root = resolve(repoRoot)

  await writeText(
    root,
    'app-version.json',
    `${JSON.stringify({ version }, null, 2)}\n`,
  )
  await writeText(
    root,
    'tms-backend/app_version.py',
    [
      '"""TOS product version shared by backend entrypoints."""',
      '',
      `APP_VERSION = "${version}"`,
      '',
    ].join('\n'),
  )
  await writeText(
    root,
    'tms-frontend/src/shared/version/appVersion.ts',
    [
      '// Generated by scripts/engineering/sync-version.mjs.',
      `export const fallbackAppVersion = '${version}'`,
      '',
    ].join('\n'),
  )

  await updateJson(root, 'tms-electron-app/package.json', (data) => {
    data.version = version
  })
  await updateJson(root, 'tms-electron-app/package-lock.json', (data) => {
    data.version = version
    if (data.packages && data.packages['']) {
      data.packages[''].version = version
    }
  })

  return version
}

async function readCurrentVersion(repoRoot = defaultRepoRoot) {
  try {
    const data = JSON.parse(await readFile(resolve(repoRoot, 'app-version.json'), 'utf8'))
    if (typeof data.version === 'string') {
      return validateAppVersion(data.version)
    }
  } catch (_error) {
    // Fall back to Electron package metadata for repositories created before app-version.json.
  }

  const packageJson = JSON.parse(
    await readFile(resolve(repoRoot, 'tms-electron-app/package.json'), 'utf8'),
  )
  return validateAppVersion(packageJson.version)
}

async function updateJson(repoRoot, relativePath, mutate) {
  const absolutePath = resolve(repoRoot, relativePath)
  const data = JSON.parse(await readFile(absolutePath, 'utf8'))
  mutate(data)
  await writeFile(absolutePath, `${JSON.stringify(data, null, 2)}\n`)
}

async function writeText(repoRoot, relativePath, content) {
  const absolutePath = resolve(repoRoot, relativePath)
  await mkdir(dirname(absolutePath), { recursive: true })
  await writeFile(absolutePath, content)
}

function readCliOptions(argv) {
  const command = argv[2]

  if (command === '--set') {
    const nextVersion = argv[3]
    if (!nextVersion) {
      throw new Error('Missing version. Usage: npm run version:set -- 0.9.8-beta.3.0')
    }
    return { mode: 'set', nextVersion }
  }

  if (command === '--bump' || !command) {
    return { mode: 'bump' }
  }

  throw new Error(`Unknown option "${command}". Use --set <version> or --bump.`)
}

async function main() {
  const options = readCliOptions(process.argv)
  const nextVersion = options.mode === 'set'
    ? options.nextVersion
    : bumpVersion(await readCurrentVersion(defaultRepoRoot))

  const syncedVersion = await syncVersion({
    repoRoot: defaultRepoRoot,
    nextVersion,
  })
  console.log(`Synced TOS version: ${syncedVersion}`)
}

const entrypoint = process.argv[1]
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error)
    process.exit(1)
  })
}
